services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - gestion-hoteles

networks:
  gestion-hoteles:
    external: true
