name: Deploy Laravel backend via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Preparar SSH hacia el servidor
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host remoto a known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Desplegar en el servidor remoto
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash -l -c '
            set -e

            cd '"${{ secrets.WORK_DIR }}"'

            # Si no está clonado aún, clona; si ya está, actualiza
            if [ ! -d .git ]; then
              git clone --branch '"${{ secrets.MAIN_BRANCH }}"' https://github.com/jesusjg3/gestionhotelera.git . 
            else
              git fetch origin
              git reset --hard origin/'"${{ secrets.MAIN_BRANCH }}"'
            fi

            # Instala/actualiza dependencias (puede ser rápido si no hay cambios)
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

            # Ejecutar migraciones pendientes (no afecta si no hay nuevas)
            php artisan migrate --force

            # Cacheos
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Recargar Apache (requiere permiso sudo sin password si es necesario)
            sudo systemctl reload apache2
          '
