name: Despliegue Laravel básico

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      PROJECT_NAME: gestionhotelera          # Cambia este nombre por tu carpeta
      BASE_PATH: /home/jesusjg3/programs # Cambia esta ruta si quieres otro path

    steps:
      - uses: actions/checkout@v2

      - name: Eliminar carpeta vieja
        run: rm -rf $BASE_PATH/$PROJECT_NAME

      - name: Copiar código a carpeta destino
        run: cp -r $GITHUB_WORKSPACE $BASE_PATH/$PROJECT_NAME

      - name: Instalar dependencias composer
        run: |
          cd $BASE_PATH/$PROJECT_NAME
          composer install --no-interaction --prefer-dist --optimize-autoloader
          
      - name: Preparar archivo .env y configurar base de datos
        run: |
          cd $BASE_PATH/$PROJECT_NAME
          if [ ! -f .env ]; then
          cp .env.example .env
          fi
          php artisan key:generate --ansi
          
          set_var() {
          local key="$1"
          local value="$2"
          if grep -qE "^[# ]*${key}=" .env; then
            sed -i "s|^[# ]*${key}=.*|${key}=${value}|" .env
          else
            echo "${key}=${value}" >> .env
          fi
          }

          set_var APP_ENV production
          set_var APP_DEBUG false
          set_var DB_CONNECTION pgsql
          set_var DB_HOST 127.0.0.1
          set_var DB_PORT 5432
          set_var DB_DATABASE gestionhoteles
          set_var DB_USERNAME gestionhoteles2024
          set_var DB_PASSWORD ubuntuhoteles2024205
