on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull_and_install:
    name: Actualizar repositorio y dependencias Composer
    runs-on: ubuntu-latest

    steps:
    - name: Instalar claves SSH
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Conectar, hacer pull e instalar dependencias Composer
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
          cd ${{ secrets.WORK_DIR }} && \
          git checkout ${{ secrets.MAIN_BRANCH }} && \
          git pull && \
          composer install && \
          exit"

    - name: Limpiar claves SSH
      run: rm -rf ~/.ssh
